version: 2
jobs:
  build:
    working_directory: /var/www/project
    docker:
      - image: kanopi/ci
    environment:
      - APACHE_DOCUMENTROOT: /var/www/project
    steps:
      - checkout
      - run:
          name: Run Composer
          command: composer install
      - run:
          name: Run Site Install
          command: |
            vendor/bin/drush site-install standard \
              -y \
              install_configure_form.enable_update_status_module=NULL \
              --db-url="mysql://user:user@localhost/default" \
              --db-su=root \
              --db-su-pw=root \
              --site-name="Test Site" \
              --site-mail="test@example.com" \
              --account-mail="test@example.com" \
              --account-name="testuser" \
              --account-pass="test123"
