version: 2
jobs:
  build:
    working_directory: /var/www/project
    docker:
      - image: kanopi/ci
        environment:
          - APACHE_DOCUMENTROOT: /var/www/project
    steps:
      - run:
          name: WHOAMI
          command: whoami
      - checkout
      - run:
          name: Run Composer
          command: composer install
      - run:
          name: Create Database
          command: |
            mysql -u root \
              -e 'CREATE DATABASE IF NOT EXISTS `default` CHARACTER SET utf8mb4;'
      - run:
          name: Fix Permissions
          command: sudo chown -R circleci:circleci /var/www/project
      - run:
          name: Copy Settings File
          command: cp sites/default/default.settings.php sites/default/settings.php | true
      - run:
          name: Run Site Install
          command: |
            drush site-install standard \
              -y \
              install_configure_form.enable_update_status_module=NULL \
              --db-url="mysql://root@127.0.0.1/default" \
              --db-su=root \
              --site-name="Test Site" \
              --site-mail="test@example.com" \
              --account-mail="test@example.com" \
              --account-name="testuser" \
              --account-pass="test123"
      - run:
          name: Test What is Installed
          command: |
            echo ${PATH}
            which npm || true
            which gem || true
            which ruby || true
            which nvm || true
            which drupal || true
            which wp-cli || true
            which backstop || true
            which grunt || true
            which gulp || true
            which lighthouse || true
            which axe-cli || true
            which yarn || true
      - run:
          name: Test Curl
          command: curl -i "http://localhost"
      - run:
          name: Added pageres CLI tool
          command: npm install -g pageres-cli
      - run:
          name: Take Screenshots
          command: pageres google.com yahoo.com localhost 1280x800 --format=jpg --filename="/tmp/artifacts/<%= date %>_<%= url %>"
      - store_artifacts:
          path: /tmp/artifacts
